#!/bin/sh

# Effortless Ctags with Git
# http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

set -e
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative --recurse \
    -f.git/tags.$$ --exclude=.git \
    --languages=-javascript,sql
mv .git/tags.$$ .git/tags
